# Generated by Django 3.0 on 2022-07-15 17:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fruitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='fruit',
            managers=[
                ('available_fruits', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='fruit',
            name='is_delete',
            field=models.SmallIntegerField(default=0),
        ),
    ]
